% Exp_06_03_01.m    Demo for handles of primary functions and subfunctions
% flag    Could be either 'line' or 'circles'
% Hr      Handles for subfunction cirline

% 20130507 XY511 21:50
% AbrahamX @ NWPU
function Hr = Exp_06_03_01(flag)

t = (0:50)/50 * 2 * pi;
x = sin(t);
y = cos(t);
Hr = @cirline;  % Handle for the subfunction
feval(Hr, flag, x, y, t)

% -------Subfunction-------
% cirline(wd,x,y,t)    Subfunction of Exp_06_03_01(flag)
% wd    Valid input could be 'line' or 'circle'
% t     Independent variable for plotting
% x     X-coordinate generated by t
% y     Y-coordinate generated by t
function cirline(wd,x,y,t)
switch wd
  case 'line'
    plot(t, x, 'b', t, y, 'r', 'LineWidth', 2)
  case 'circle'
    plot(x, y, '-g', 'LineWidth', 8)
    axis square off
  otherwise 
    error('Buddy! Valid specification could ONLY be "line" or "circle"!')
end
shg
