% 20130425 XY511 10:35
% AbrahamX @ NWPU
% f(x) = \int_0^x(1/log(t)) dt. Plot f(x), 0<=x<=0.9

% WARNING: f(x) has no definition when x = 0
syms t x positive
gt = 1/log(t);
% x cannot equal 0, so have to consider the limit.
gt_0 = limit(gt, t, 0, 'right')  

% Ezplot and see whether f(x) could be integrated or not.
ezplot(gt, [0,1])  % Required is [0, 0.9], make it [0, 1]
grid on
legend('gt')

% F(x) = int(f(x)). Let's find F(x). (In this program it's gt)
fx = subs(int(gt, t), t, 'x')

% Use command mfun to calc definite integral when x is different
x = 0: 0.05: 0.9;
fxMfun = mfun('Li', x)  % Li is a function definedin MuPAD

% Plot based on the codes & data just above
hold on
plot(x, fxMfun, '--r', 'LineWidth', 3)
legend('gt', 'fxMfun', 'Location', 'Best')
title(' ')  % clear the title generated by ezplot
title('\int_0^x 1/(log(x))dt Primitive function & Integrated function')
hold off

% Withnin \toolbox\matlab\specfun, there is a "expint" command
% So call it and compare the results.
% WARNING: expint & Li has DIFFERENT definition. Consult "HELP"
% for more information before caling them.
fx_matlab = -expint(-log(x))