function y = Exp_02_09_01_Auto(x,a,b,yL,yR)
%EXP_02_09_01_AUTO
%    Y = EXP_02_09_01_AUTO(X,A,B,YL,YR)
%    Two-Point Boundary Value Problem, programmed to find its 
%    numerical solutions.
%    x        Array for independent variable
%    a,b      x-coordinate for the left and right boundary value
%    yL,yR    y-coordinate for the left and right boundary value
%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    25-Apr-2013 09:29:12

t2 = a.^2;
t3 = b.^2;
t4 = t2.^2;
t5 = t3.^2;
t6 = x.^2;
t7 = t4-t5;
t8 = 1.0./t7;
y = -t8.*(t5.*yL-t4.*yR+a.*t2.*t5.*(1.0./3.0)-b.*t3.*t4.*(1.0./3.0))-t6.*x.*(1.0./3.0)+t6.^2.*t8.*(yL-yR+a.*t2.*(1.0./3.0)-b.*t3.*(1.0./3.0));
